name: weekly CI test run
on:
  workflow_call:
    inputs:
      run_number:
        required: true
        type: string

concurrency:
  group: ci-run-${{ inputs.run_number }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: commaai/openpilot/.github/workflows/tests.yaml@ci25
    with:
      run_number: ${{ inputs.run_number }}
